[package]
name = "conjure-rust"
version.workspace = true
authors = ["Steven Fackler <sfackler@palantir.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
clap = { version = "4", features = ["derive"] }

conjure-codegen = { version = "4.0.0-rc3", path = "../conjure-codegen" }
