[package]
name = "conjure-rust"
version = "0.7.2"
authors = ["Steven Fackler <sfackler@palantir.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
structopt = "0.3"

conjure-codegen = { version = "0.7.2", path = "../conjure-codegen" }
