[package]
name = "conjure-rust"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@palantir.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
structopt = "0.2"

conjure-codegen = { version = "0.1", path = "../conjure-codegen" }
