[package]
name = "conjure-test"
version = "0.3.4"
authors = ["Steven Fackler <sfackler@palantir.com>"]
edition = "2018"

[lib]
doctest = false

[dependencies]
conjure-object = { path = "../conjure-object" }
conjure-error = { path = "../conjure-error" }
conjure-http = { path = "../conjure-http" }

[dev-dependencies]
serde = "1.0"
serde_json = "1.0"
base64 = "0.10"
http = "0.1"

conjure-serde = { path = "../conjure-serde" }

[build-dependencies]
conjure-codegen = { path = "../conjure-codegen" }
